# Android CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-android/ for more details
#

aliases:
  - &restore-cache
    keys:
      - jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

defaults: &defaults
    working_directory: ~/aegis

android_defaults: &android_defaults
    <<: *defaults
    docker:
    - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m

version: 2
jobs:

  build:
    <<: *android_defaults
    steps:
    - checkout
    - restore_cache: *restore-cache
    - run:
        name: Download Dependencies
        command: ./gradlew androidDependencies
    - save_cache:
        paths:
        - ~/.gradle
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

  lints:
    <<: *android_defaults
    steps:
    - checkout
    - restore_cache: *restore-cache
    - run:
        name: Run Lint Test
        command: ./gradlew lint
    - run:
        name: Run detekt
        command: ./gradlew detektCheck
    - run:
        name: Run ktLint
        command: ./gradlew ktLint

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
    - build
    - lints:
        requires:
        - build